# Generated by Django 5.0.6 on 2024-08-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categrory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='categrory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='categrory',
            new_name='category',
        ),
    ]
