# Generated by Django 5.0.6 on 2024-08-27 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_categrory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='off',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.BooleanField(default=False, help_text='@-default,1-Trending')),
                ('seconds', models.BooleanField(default=False, help_text='@-default,1-Trending')),
                ('third', models.BooleanField(default=False, help_text='@-default,1-Trending')),
                ('forth', models.BooleanField(default=False, help_text='@-default,1-Trending')),
                ('fifth', models.BooleanField(default=False, help_text='@-default,1-Trending')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productmodel')),
            ],
        ),
    ]
