# Generated by Django 5.0.6 on 2024-08-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productmodel_off_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='fifth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='forth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='seconds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='third',
            field=models.BooleanField(default=False),
        ),
    ]
