# Generated by Django 5.0.6 on 2024-08-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_promotions_fifth_alter_promotions_first_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back', models.ImageField(upload_to='assets/img/')),
                ('first', models.BooleanField(default=False)),
                ('seconds', models.BooleanField(default=False)),
                ('third', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productmodel')),
            ],
        ),
    ]
