# Generated by Django 5.0.6 on 2024-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Watch', 'Watch'), ('Gadget', 'Gadget'), ('Speaker', 'Speaker'), ('Accessories', 'Accessories'), ('Computer', 'Computer'), ('TV', 'TV')], max_length=100),
        ),
    ]
