# Generated by Django 5.0.6 on 2024-08-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_productmodel_item_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='assets/img/')),
            ],
        ),
    ]
